# Laboratory Task 5 — PyTorch Tensor Basics

**Course Topic:** PyTorch Basics

> This laboratory exercise applies fundamental PyTorch tensor operations, including NumPy conversion, data type conversion, reshaping, indexing, arithmetic operations, random tensor generation, and matrix multiplication.

---
## Task 1 — Perform Standard Imports

We import **NumPy** (used to create the initial random array) and **PyTorch** (used for all tensor operations).

In [1]:
import numpy as np
import torch

print("NumPy version:  ", np.__version__)
print("PyTorch version:", torch.__version__)

NumPy version:   1.26.4
PyTorch version: 2.8.0+cpu


---
## Task 2 — Create the `set_seed()` Function

This function sets the random seed for both NumPy and PyTorch so that any random values generated afterward are reproducible. Both libraries maintain separate random number generators, so both need to be seeded.

In [2]:
def set_seed(seed: int) -> None:
    """Set the random seed for NumPy and PyTorch."""
    np.random.seed(seed)
    torch.manual_seed(seed)

The function accepts an integer seed, sets it for both libraries, and returns nothing. Calling `set_seed(42)` before generating random values ensures the same sequence is produced every time the notebook is run.

---
## Task 3 — Create a Random NumPy Array

We generate a NumPy array called `arr` containing **6 random integers** between 0 (inclusive) and 5 (exclusive), using seed 42 for reproducibility. The array is explicitly stored as `int32` so that the required dtype conversion can be demonstrated in a later task.

In [3]:
# Set the seed so random values are reproducible
set_seed(42)

# 6 random integers in [0, 5)
arr = np.random.randint(0, 5, size=6).astype(np.int32)

print("arr:  ", arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)

arr:   [3 4 2 4 4 1]
dtype: int32
shape: (6,)


---
## Task 4 — Convert `arr` into Tensor `x`

We use `torch.from_numpy()` to create a PyTorch tensor from the NumPy array. This method can share underlying memory with the source array, a concept discussed in the original lesson.

In [4]:
x = torch.from_numpy(arr)

print("x:    ", x)
print("type: ", type(x))
print("dtype:", x.dtype)

x:     tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
type:  <class 'torch.Tensor'>
dtype: torch.int32


The tensor `x` inherits the `int32` data type from the NumPy array.

---
## Task 5 — Change the Data Type of `x`

The task requires converting `x` from `int32` to `int64`. This is done using `.type()`, which returns a new tensor with the specified dtype.

In [5]:
print("Before:", x.dtype)

x = x.type(torch.int64)

print("After: ", x.dtype)

Before: torch.int32
After:  torch.int64


---
## Task 6 — Reshape `x` into a 3 × 2 Tensor

The tensor `x` contains 6 elements, and $3 \times 2 = 6$, so reshaping into a 3×2 tensor is valid. Reshaping changes the arrangement of elements without changing the total count.

In [6]:
x = x.reshape(3, 2)

print(x)
print("Shape:", x.shape)

tensor([[3, 4],
        [2, 4],
        [4, 1]])
Shape: torch.Size([3, 2])


---
## Task 7 — Return the Right-Hand Column of `x`

Since `x` now has shape (3, 2), the right-hand column is column index 1. Using `x[:, 1:]` selects all rows and columns from index 1 onward, preserving the 2-D shape as a column tensor.

In [7]:
right_column = x[:, 1:]

print("Right-hand column:")
print(right_column)
print("Shape:", right_column.shape)

Right-hand column:
tensor([[4],
        [4],
        [1]])
Shape: torch.Size([3, 1])


The `1:` slice keeps the result as a 2-D tensor with shape (3, 1), rather than collapsing it to a 1-D tensor of shape (3,) as `x[:, 1]` would.

---
## Task 8 — Square the Values of `x`

The instruction says "without changing `x`," so we use a non-in-place operation. The `**` operator squares each element independently (element-wise), which is different from matrix multiplication.

In [8]:
x_squared = x ** 2

print("Original x:")
print(x)

print("\nSquared values:")
print(x_squared)

Original x:
tensor([[3, 4],
        [2, 4],
        [4, 1]])

Squared values:
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


Confirmed: `x` remains unchanged after the squaring operation.

---
## Task 9 — Create Tensor `y` for Matrix Multiplication

Tensor `y` must satisfy four constraints:

1. Contains the **same number of elements** as `x` (which is 6).
2. Created using **PyTorch** (not NumPy).
3. Contains random integers from **0 inclusive to 5 exclusive**.
4. Its shape must permit **matrix multiplication** with `x`.

### Shape Reasoning

For matrix multiplication $A_{m \times n} \cdot B_{n \times p}$, the inner dimensions must match.

Since $x$ has shape $(3 \times 2)$, the first dimension of $y$ must be **2** (to match the 2 columns of $x$).

Since $y$ must also contain exactly 6 elements:

$$2 \times 3 = 6$$

Therefore $y$ must have shape $(2 \times 3)$, and the result will be:

$$(3 \times 2) \cdot (2 \times 3) = (3 \times 3)$$

In [9]:
# Reuse the seed function for consistency
set_seed(42)

# y must be 2x3 so its rows match x's 2 columns
y = torch.randint(0, 5, (2, 3))

print("y:")
print(y)
print("Shape:             ", y.shape)
print("Number of elements:", y.numel())

y:
tensor([[2, 2, 1],
        [4, 1, 0]])
Shape:              torch.Size([2, 3])
Number of elements: 6


---
## Task 10 — Find the Matrix Product of `x` and `y`

Before multiplying, we confirm the shapes are compatible.

In [10]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: torch.Size([3, 2])
y shape: torch.Size([2, 3])


$(3 \times 2) \cdot (2 \times 3)$ is valid because the inner dimensions (2) match. The resulting matrix will have shape $(3 \times 3)$.

In [11]:
matrix_product = torch.mm(x, y)

print("Matrix product (x @ y):")
print(matrix_product)
print("Result shape:", matrix_product.shape)

Matrix product (x @ y):
tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
Result shape: torch.Size([3, 3])


We can verify the same result using the `@` operator:

In [12]:
# Equivalent using the @ operator
print(x @ y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


---
## Summary of Results

In [13]:
print(f"Task 3  | arr shape:        {arr.shape}")
print(f"Task 3  | arr dtype:        {arr.dtype}")
print(f"Task 5  | x dtype:          {x.dtype}")
print(f"Task 6  | x shape:          {x.shape}")
print(f"Task 7  | Right column:     {right_column}")
print(f"Task 8  | x² shape:         {x_squared.shape}")
print(f"Task 9  | y shape:          {y.shape}")
print(f"Task 9  | y elements:       {y.numel()}")
print(f"Task 10 | x @ y shape:      {matrix_product.shape}")

Task 3  | arr shape:        (6,)
Task 3  | arr dtype:        int32
Task 5  | x dtype:          torch.int64
Task 6  | x shape:          torch.Size([3, 2])
Task 7  | Right column:     tensor([[4],
        [4],
        [1]])
Task 8  | x² shape:         torch.Size([3, 2])
Task 9  | y shape:          torch.Size([2, 3])
Task 9  | y elements:       6
Task 10 | x @ y shape:      torch.Size([3, 3])


| Task | Operation | Result / Property |
| :---: | :--- | :--- |
| 1 | Standard imports | `numpy`, `torch` |
| 2 | Random seed | 42 (NumPy + PyTorch) |
| 3 | NumPy array `arr` | 6 integers from [0, 5) |
| 4 | Tensor `x` | Created from `arr` via `torch.from_numpy()` |
| 5 | `x` dtype | `torch.int64` |
| 6 | `x` shape | (3, 2) |
| 7 | Right-hand column | Sliced with `x[:, 1:]` → shape (3, 1) |
| 8 | Squared values | Element-wise `x ** 2` |
| 9 | Tensor `y` shape | (2, 3) — 6 elements |
| 10 | Matrix product | `torch.mm(x, y)` → shape (3, 3) |

---
## Conclusion

This laboratory demonstrated how tensors can be created, reshaped, indexed, and used in mathematical operations in PyTorch. Setting a random seed before generating values ensured that results are reproducible across runs. Converting a NumPy array to a PyTorch tensor with `torch.from_numpy()` showed the bridge between the two libraries, and changing the data type from `int32` to `int64` illustrated how tensor dtypes can be managed.

Reshaping and slicing operations showed how to rearrange and extract parts of a tensor without changing the underlying data. Element-wise squaring demonstrated that arithmetic operators like `**` act on each value independently, which is fundamentally different from matrix multiplication. Finally, determining the correct shape for tensor `y` — reasoning that a (3×2) matrix can only be multiplied by a (2×3) matrix to satisfy both the dimension rule and the 6-element constraint — was the key reasoning exercise of this laboratory.